minimal_mistakes_skin: "sunrise"

title: Indigenous Language Robots Documentation
email:
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for the Indigenous Language Robots Project
baseurl: /ILR
url: https://coedl.github.io
#twitter_username: mmistakes
#github_username: mmistakes

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
#timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
search: false

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

#author:
#  name   : "Michael Rose"
#  avatar : "/assets/images/bio-photo.jpg"
#  bio    : "My awesome biography constrained to a sentence or two goes here."
#  email  : # optional
#  uri    : 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
include:
  - _docs
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      author_profile: false
      comments: true
      share: true
      toc: true
      sidebar:
        - title: "Title"
          image: http://placehold.it/350x250
          image_alt: "image"
          text: "Some text here."
        - title: "Another Title"
          text: "More text here."
      related: true
